In [ ]:
import pandas as pd
from sklearn.datasets import load_iris
#Membaca file survey lung cancer.csv
iris = pd.read_csv('survey lung cancer.csv')

In [ ]:
# Melihat informasi dataset
iris.info()

# melihat informasi dataset pada 5 baris pertama
iris.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [ ]:
iris.columns = ["Gender", "Age", "Smoking", "Yellow Fingers", "Anxiety", "Peer Pressure",
              "Chronic Disease", "Fatigue", "Allergy", "Wheezing", "Alcohol Consuming", "Coughing", "Shortness of Breath", "Swallowing Difficulty", "Chest Pain", "Lung Cancer"]

In [ ]:
#transforming dataset with dummies variables to replace characters with binary integers
iris["Gender"].replace(["M","F"], [1,2], inplace=True)

#memisahkan atribut dan label
X = iris[["Gender", "Age", "Smoking", "Yellow Fingers", "Anxiety", "Peer Pressure", "Chronic Disease", "Fatigue", "Allergy", "Wheezing", "Alcohol Consuming", "Coughing", "Shortness of Breath", "Swallowing Difficulty", "Chest Pain"]]
y = iris["Lung Cancer"]

#Membagi dataset menjadi data latih & data uji
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=123)

In [ ]:
iris.head()

,Gender,Age,Smoking,Yellow Fingers,Anxiety,Peer Pressure,Chronic Disease,Fatigue,Allergy,Wheezing,Alcohol Consuming,Coughing,Shortness of Breath,Swallowing Difficulty,Chest Pain,Lung Cancer
0,1,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,1,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,2,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [ ]:
from sklearn.tree import DecisionTreeClassifier

#membuat model Decision Tree
tree_model = DecisionTreeClassifier()

#melatih model dengan menggunakan data latih
tree_model = tree_model.fit(X_train, y_train)

#Evaluasi Model
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

y_pred = tree_model.predict(X_test)

acc_secore = round(accuracy_score(y_pred, y_test), 3)

print('Accuracy: ', acc_secore)
print('classification report')
print(classification_report(y_pred, y_test))

Accuracy:  0.903
classification report
              precision    recall  f1-score   support

          NO       0.67      0.50      0.57         4
         YES       0.93      0.96      0.95        27

    accuracy                           0.90        31
   macro avg       0.80      0.73      0.76        31
weighted avg       0.89      0.90      0.90        31

In [ ]:
# prediksi model degnan tree_model.predict([["Gender", "Age", "Smoking", "Yellow Fingers", "Anxiety", "Peer Pressure", "Chronic Disease", "Fatigue", "Allergy", "Wheezing", "Alcohol Consuming", "Coughing", "Shortness of Breath", "Swallowing Difficulty", "Chest Pain"]])
print(tree_model.predict([[1, 63, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2]])[0])

YES

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
from sklearn.tree import export_graphviz
export_graphviz(
    tree_model,
    out_file = "lungcancer_tree.dot",
    feature_names=["Gender", "Age", "Smoking", "Yellow Fingers", "Anxiety", "Peer Pressure", "Chronic Disease", "Fatigue", "Allergy", "Wheezing", "Alcohol Consuming", "Coughing", "Shortness of Breath", "Swallowing Difficulty", "Chest Pain"],
    class_names=["NO", "YES"],
    rounded=True,
    filled=True
)

In [ ]:
from subprocess import check_call
check_call(['dot', '-Tpng', 'lungcancer_tree.dot', '-o', 'lungcancer_tree.png'])

0